import crypto from 'node:crypto';
import fs from 'node:fs';
import { db } from './db.js';
import { createGeneratedAsset, createUploadedAsset, findAsset, listAssets, activateAsset } from './assets.js';
import { generateImage, refineImage, type ImageGenerationRequest } from './providers.js';
import { getSelectedConcept } from './visual-concepts.js';
import { getVisualIdentity } from './visual-identity.js';
import { platformPresets, type PlatformId } from './platform-presets.js';

export type ArtworkType = 'thumbnail'|'cover'|'canvas';
const row = (id:string) => db.prepare('SELECT * FROM project_artwork WHERE id=?').get(id) as any;
export function listArtwork(projectId:string) { return (db.prepare('SELECT * FROM project_artwork WHERE project_id=? ORDER BY updated_at DESC').all(projectId) as any[]).map(asArtwork); }
function asArtwork(item:any) { const source=item.source_asset_id ? findAsset(item.source_asset_id) : null; return { id:item.id, type:item.type, platform:item.platform, activeAssetId:item.active_asset_id, sourceAssetId:item.source_asset_id ?? null, source:item.source, sourceImage:source ? {id:source.id,url:source.url}:null, textConfig:JSON.parse(item.text_config || '{}'), createdAt:item.created_at, updatedAt:item.updated_at, variants:listAssets('artwork', item.id) }; }
function ensure(projectId:string, platform:PlatformId, type:ArtworkType='thumbnail', source='project') { const existing=db.prepare('SELECT id FROM project_artwork WHERE project_id=? AND platform=? AND type=?').get(projectId,platform,type) as any; if(existing) return existing.id; const id=crypto.randomUUID(), now=new Date().toISOString(); db.prepare('INSERT INTO project_artwork(id,project_id,type,platform,source,text_config,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,projectId,type,platform,source,'{}',now,now); return id; }
export function updateArtwork(projectId:string,id:string,input:{activeAssetId?:string;textConfig?:unknown}) { const item=row(id); if(!item||item.project_id!==projectId) return null; if(input.activeAssetId){ const asset=activateAsset(projectId,'artwork',id,input.activeAssetId); if(!asset) throw new Error('Artwork version not found.'); db.prepare('UPDATE project_artwork SET active_asset_id=?,updated_at=? WHERE id=?').run(asset.id,new Date().toISOString(),id); } if(input.textConfig!==undefined) db.prepare('UPDATE project_artwork SET text_config=?,updated_at=? WHERE id=?').run(JSON.stringify(input.textConfig),new Date().toISOString(),id); return asArtwork(row(id)); }
function context(project:any, platform:PlatformId, strategy:string, focus:string, text:string, subtitle:string) { const concept=getSelectedConcept(project.id), identity=getVisualIdentity(project.id), shots=db.prepare('SELECT title,description,action,mood FROM shots WHERE project_id=? ORDER BY position').all(project.id) as any[]; const p=platformPresets[platform]; const summary=shots.slice(0,8).map(s=>`${s.title}: ${s.description}`).join('; '); return `Create representative music-video ${p.artworkType} artwork. Project: ${project.title}. Song context: ${project.suno_description || project.lyrics?.slice(0,2000) || ''}. Selected concept: ${concept ? `${concept.title}; ${concept.description}; ${concept.mood}; ${concept.visualStyle}` : project.visual_style}. Visual identity: ${identity.style.description}. Storyboard highlights: ${summary}. Creative strategy: ${strategy}. Thumbnail focus: ${focus}. ${text ? 'Leave clean negative space for a title overlay that will be applied separately by the app.' : 'No text treatment is required.'} Never render words, letters, signs, posters, captions, logos, or typography in the image. ${p.compositionGuidance} ${p.safeArea} Do not include watermarks or UI.`; }
function request(project:any, platform:PlatformId, prompt:string):ImageGenerationRequest { const p=platformPresets[platform]; return { projectId:project.id,shotId:`artwork-${platform}`,aspectRatio:p.aspectRatio,visualStyle:project.visual_style,concept:null,description:'Project artwork',action:'',shotType:'',camera:'',mood:'',characters:[],location:null,previousShot:null,referenceContext:{characters:[],location:null,style:{id:'style',type:'style',name:'Visual style',description:project.visual_style,imageAsset:null,locked:false,stale:false},continuityReference:null},generationInstructions:p.compositionGuidance,prompt,qualityPreset:project.image_quality_preset,modelOverride:project.image_model_override,resolutionOverride:p.preferredResolution }; }
export async function generateArtwork(project:any,input:{platform:PlatformId;count:number;strategy:string;focus:string;text:string;subtitle:string;sourceAssetId?:string}) { const id=ensure(project.id,input.platform); for(let index=0;index<input.count;index++){ const diversity=['Character-focused','Motif-focused','Cinematic environment','High-impact dramatic'][index] || input.strategy; const prompt=context(project,input.platform,`${input.strategy}; explore ${diversity}`,input.focus,input.text,input.subtitle); const result=await generateImage(project.image_provider,request(project,input.platform,prompt)); const asset=await createGeneratedAsset({projectId:project.id,ownerType:'artwork',ownerId:id,url:result.url,provider:project.image_provider,model:result.model,quality:result.quality,resolution:result.resolution}); db.prepare('UPDATE project_artwork SET active_asset_id=?,updated_at=? WHERE id=?').run(asset.id,new Date().toISOString(),id); } return asArtwork(row(id)); }
export function uploadArtwork(projectId:string,platform:PlatformId,file:{buffer:Buffer;mimetype:string;originalname:string}) { const id=ensure(projectId,platform,'thumbnail','upload'); const asset=createUploadedAsset({projectId,ownerType:'artwork',ownerId:id,data:file.buffer,mimeType:file.mimetype,originalFilename:file.originalname}); db.prepare('UPDATE project_artwork SET active_asset_id=?,updated_at=? WHERE id=?').run(asset.id,new Date().toISOString(),id); return asArtwork(row(id)); }
export function useSourceAsArtwork(projectId:string,platform:PlatformId,sourceAssetId:string) { const source=findAsset(sourceAssetId); if(!source||source.projectId!==projectId) throw new Error('Source image not found.'); const id=ensure(projectId,platform); db.prepare("UPDATE project_artwork SET source_asset_id=?, source='storyboard', updated_at=? WHERE id=?").run(source.id,new Date().toISOString(),id); return asArtwork(row(id)); }
export function deleteArtworkAsset(projectId:string, artworkId:string, assetId:string) { const artwork=row(artworkId); const asset=findAsset(assetId); if(!artwork||artwork.project_id!==projectId||!asset||asset.projectId!==projectId||asset.ownerType!=='artwork'||asset.ownerId!==artworkId) return null; fs.unlinkSync(asset.storagePath); db.prepare('DELETE FROM image_assets WHERE id=?').run(assetId); const replacement=listAssets('artwork',artworkId)[0] ?? null; if(replacement) activateAsset(projectId,'artwork',artworkId,replacement.id); db.prepare('UPDATE project_artwork SET active_asset_id=?,updated_at=? WHERE id=?').run(replacement?.id ?? null,new Date().toISOString(),artworkId); return asArtwork(row(artworkId)); }
export async function refineArtwork(project:any,id:string,instruction:string) { const item=row(id); if(!item||item.project_id!==project.id||!item.active_asset_id) throw new Error('Choose an artwork version first.'); const asset=findAsset(item.active_asset_id)!; const p=platformPresets[item.platform as PlatformId]; const result=await refineImage(project.image_provider,request(project,item.platform,`${context(project,item.platform,'Refined', 'Automatic','','')} Refine the supplied image: ${instruction}. Preserve character identity, location, and intent.`),fs.readFileSync(asset.storagePath),asset.originalFilename || 'artwork.png'); const next=await createGeneratedAsset({projectId:project.id,ownerType:'artwork',ownerId:id,url:result.url,provider:project.image_provider,model:result.model,quality:result.quality,resolution:result.resolution}); db.prepare('UPDATE project_artwork SET active_asset_id=?,updated_at=? WHERE id=?').run(next.id,new Date().toISOString(),id); return asArtwork(row(id)); }
