import crypto from 'node:crypto';
import fs from 'node:fs';
import { db } from './db.js';
import { createGeneratedAsset, createUploadedAsset, findAsset, listAssets, activateAsset } from './assets.js';
import { generateImage, refineImage, type ImageGenerationRequest } from './providers.js';
import { getConcept, getSelectedConcept, requireSelectedConceptId } from './visual-concepts.js';
import { getVisualIdentity } from './visual-identity.js';
import { platformPresets, type PlatformId } from './platform-presets.js';
import sharp from 'sharp';
import type { ImageQuality } from './provider-settings.js';
import { buildProjectContext, projectType } from './project-context.js';

export type ArtworkType = 'thumbnail'|'cover'|'canvas';
type ArtworkTextConfig = { title:string; subtitle:string; style:'Bold impact'|'Neon glow'|'Elegant serif'|'Handwritten'|'Clean minimal'; mood:'Energetic'|'Romantic'|'Dark'|'Dreamy'|'Epic' };
const escapeXml = (value:string) => value.replace(/[<>&"']/g, character => ({ '<':'&lt;', '>':'&gt;', '&':'&amp;', '"':'&quot;', "'":'&apos;' }[character]!));
const wrapTitle = (title:string, limit=18) => { const words=title.trim().split(/\s+/); const lines:string[]=[]; let line=''; for(const word of words){ const next=line ? `${line} ${word}` : word; if(line && next.length>limit){ lines.push(line); line=word; } else line=next; } if(line) lines.push(line); return lines.slice(0,3); };
async function addTextTreatment(data:Buffer, config:ArtworkTextConfig) { if(!config.title.trim()) return data; const metadata=await sharp(data).metadata(); const width=metadata.width || 1536, height=metadata.height || 1024; const size=Math.round(Math.min(width,height)*.115); const palette={Energetic:'#ffd60a',Romantic:'#ff88b7',Dark:'#e9edf4',Dreamy:'#9be7ff',Epic:'#f8d68a'}[config.mood]; const style=config.style==='Neon glow' ? `font-family="sans-serif" font-style="italic" fill="${palette}" stroke="#ff2ca5" stroke-width="2" paint-order="stroke"` : config.style==='Elegant serif' ? `font-family="serif" fill="#fff5dc" stroke="#27170e" stroke-width="2" paint-order="stroke"` : config.style==='Handwritten' ? `font-family="cursive" font-style="italic" fill="#ffffff" stroke="#171717" stroke-width="3" paint-order="stroke"` : config.style==='Clean minimal' ? `font-family="sans-serif" fill="#ffffff"` : `font-family="Impact, sans-serif" font-weight="900" fill="#ffffff" stroke="#111111" stroke-width="${Math.max(3,Math.round(size*.08))}" paint-order="stroke"`; const lines=wrapTitle(config.title).map((line,index)=>`<tspan x="${width/2}" dy="${index ? size*.88 : 0}">${escapeXml(line)}</tspan>`).join(''); const subtitle=config.subtitle.trim() ? `<text x="${width/2}" y="${height-size*.45}" text-anchor="middle" font-family="sans-serif" font-size="${Math.round(size*.28)}" font-weight="700" letter-spacing="${Math.round(size*.04)}" fill="${palette}">${escapeXml(config.subtitle.toUpperCase())}</text>` : ''; const top=height-size*(config.subtitle.trim()?1.2:0.7)-Math.max(0,wrapTitle(config.title).length-1)*size*.88; const svg=`<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="shade" x1="0" y1="0" x2="0" y2="1"><stop offset="55%" stop-color="#000" stop-opacity="0"/><stop offset="100%" stop-color="#000" stop-opacity=".7"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#shade)"/><text x="${width/2}" y="${top}" text-anchor="middle" font-size="${size}" ${style}>${lines}</text>${subtitle}</svg>`; return sharp(data).composite([{input:Buffer.from(svg),top:0,left:0}]).png().toBuffer(); }
const row = (id:string) => db.prepare('SELECT * FROM project_artwork WHERE id=?').get(id) as any;
export function listArtwork(projectId:string) { const conceptId=getSelectedConcept(projectId)?.id; return conceptId ? (db.prepare('SELECT * FROM project_artwork WHERE project_id=? AND concept_id=? ORDER BY updated_at DESC').all(projectId,conceptId) as any[]).map(asArtwork) : []; }
function asArtwork(item:any) { const source=item.source_asset_id ? findAsset(item.source_asset_id) : null; return { id:item.id, type:item.type, platform:item.platform, activeAssetId:item.active_asset_id, sourceAssetId:item.source_asset_id ?? null, source:item.source, sourceImage:source ? {id:source.id,url:source.url}:null, textConfig:JSON.parse(item.text_config || '{}'), createdAt:item.created_at, updatedAt:item.updated_at, variants:listAssets('artwork', item.id) }; }
function ensure(projectId:string, platform:PlatformId, type:ArtworkType='thumbnail', source='project') { const conceptId=requireSelectedConceptId(projectId); const existing=db.prepare('SELECT id FROM project_artwork WHERE project_id=? AND concept_id=? AND platform=? AND type=?').get(projectId,conceptId,platform,type) as any; if(existing) return existing.id; const id=crypto.randomUUID(), now=new Date().toISOString(); db.prepare('INSERT INTO project_artwork(id,project_id,concept_id,type,platform,source,text_config,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,projectId,conceptId,type,platform,source,'{}',now,now); return id; }
export function updateArtwork(projectId:string,id:string,input:{activeAssetId?:string;textConfig?:unknown}) { const item=row(id),conceptId=requireSelectedConceptId(projectId); if(!item||item.project_id!==projectId||item.concept_id!==conceptId) return null; if(input.activeAssetId){ const asset=activateAsset(projectId,'artwork',id,input.activeAssetId); if(!asset) throw new Error('Artwork version not found.'); db.prepare('UPDATE project_artwork SET active_asset_id=?,updated_at=? WHERE id=?').run(asset.id,new Date().toISOString(),id); } if(input.textConfig!==undefined) db.prepare('UPDATE project_artwork SET text_config=?,updated_at=? WHERE id=?').run(JSON.stringify(input.textConfig),new Date().toISOString(),id); return asArtwork(row(id)); }
function context(project:any, conceptId:string, platform:PlatformId, strategy:string, focus:string, customStylePrompt:string, text:string, subtitle:string) { const concept=getConcept(project.id,conceptId); if(!concept) throw new Error('Visual concept not found.'); const identity=getVisualIdentity(project.id,concept.id), shots=db.prepare('SELECT title,description,action,mood FROM shots WHERE project_id=? AND concept_id=? ORDER BY position').all(project.id,concept.id) as any[]; const p=platformPresets[platform]; const summary=shots.slice(0,8).map(s=>`${s.title}: ${s.description}`).join('; '); const visualStyle=identity.style.description || project.visual_style; const customDirection=customStylePrompt ? ` User custom art direction: ${customStylePrompt}. Prioritize this direction while remaining consistent with the locked visual identity.` : ''; return `Create representative ${projectType(project) === 'music_video' ? 'music-video ' : ''}${p.artworkType} artwork. Project: ${project.title}. ${buildProjectContext(project)} Selected concept: ${concept.title}; ${concept.description}; ${concept.mood}; ${concept.visualStyle}. Visual identity: ${visualStyle}.${customDirection} Storyboard highlights: ${summary}. Creative strategy: ${strategy}. Artwork focus: ${focus}. ${text ? 'Leave clean negative space for a title overlay that will be applied separately by the app.' : 'No text treatment is required.'} Never render words, letters, signs, posters, captions, logos, or typography in the image. ${p.compositionGuidance} ${p.safeArea} Do not include watermarks or UI.`; }
function request(project:any, conceptId:string, platform:PlatformId, prompt:string, qualityPreset?:ImageQuality):ImageGenerationRequest { const p=platformPresets[platform], identity=getVisualIdentity(project.id,conceptId), visualStyle=identity.style.description || project.visual_style; return { projectId:project.id,shotId:`artwork-${platform}`,aspectRatio:p.aspectRatio,visualStyle,concept:null,description:'Project artwork',action:'',shotType:'',camera:'',mood:'',characters:[],location:null,previousShot:null,referenceContext:{characters:[],location:null,style:{id:'visual-style',type:'style',name:'Visual Style',description:visualStyle,imageAsset:identity.style.locked ? identity.style.image_url : null,locked:identity.style.locked,stale:identity.style.image_outdated},continuityReference:null},generationInstructions:p.compositionGuidance,prompt,qualityPreset:qualityPreset ?? project.image_quality_preset,modelOverride:project.image_model_override,resolutionOverride:p.preferredResolution }; }
export async function generateArtwork(project:any,input:{platform:PlatformId;count:number;strategy:string;focus:string;customStylePrompt:string;text:string;subtitle:string;textConfig?:ArtworkTextConfig;sourceAssetId?:string;qualityPreset?:ImageQuality}) { const id=ensure(project.id,input.platform),conceptId=(row(id) as any).concept_id; const textConfig=input.textConfig ?? {title:input.text,subtitle:input.subtitle,style:'Bold impact',mood:'Epic'}; db.prepare('UPDATE project_artwork SET text_config=?,updated_at=? WHERE id=?').run(JSON.stringify(textConfig),new Date().toISOString(),id); for(let index=0;index<input.count;index++){ const diversity=['Character-focused','Motif-focused','Cinematic environment','High-impact dramatic'][index] || input.strategy; const prompt=context(project,conceptId,input.platform,`${input.strategy}; explore ${diversity}`,input.focus,input.customStylePrompt,textConfig.title,textConfig.subtitle); const result=await generateImage(project.image_provider,request(project,conceptId,input.platform,prompt,input.qualityPreset)); const original=await fetch(result.url).then(response=>response.arrayBuffer()).then(buffer=>Buffer.from(buffer)); const treated=await addTextTreatment(original,textConfig); const asset=await createGeneratedAsset({projectId:project.id,ownerType:'artwork',ownerId:id,url:`data:image/png;base64,${treated.toString('base64')}`,provider:result.provider,model:result.model,quality:result.quality,resolution:result.resolution,tier:result.tier,originalFilename:'thumbnail.png'}); db.prepare('UPDATE project_artwork SET active_asset_id=?,updated_at=? WHERE id=?').run(asset.id,new Date().toISOString(),id); } return asArtwork(row(id)); }
export function uploadArtwork(projectId:string,platform:PlatformId,file:{buffer:Buffer;mimetype:string;originalname:string}) { const id=ensure(projectId,platform,'thumbnail','upload'); const asset=createUploadedAsset({projectId,ownerType:'artwork',ownerId:id,data:file.buffer,mimeType:file.mimetype,originalFilename:file.originalname}); db.prepare('UPDATE project_artwork SET active_asset_id=?,updated_at=? WHERE id=?').run(asset.id,new Date().toISOString(),id); return asArtwork(row(id)); }
export function useSourceAsArtwork(projectId:string,platform:PlatformId,sourceAssetId:string) { const source=findAsset(sourceAssetId),conceptId=requireSelectedConceptId(projectId); if(!source||source.projectId!==projectId||source.conceptId!==conceptId) throw new Error('Choose a source image from the selected concept.'); const id=ensure(projectId,platform); db.prepare("UPDATE project_artwork SET source_asset_id=?, source='storyboard', updated_at=? WHERE id=?").run(source.id,new Date().toISOString(),id); return asArtwork(row(id)); }
export function deleteArtworkAsset(projectId:string, artworkId:string, assetId:string) { const artwork=row(artworkId),conceptId=requireSelectedConceptId(projectId); const asset=findAsset(assetId); if(!artwork||artwork.project_id!==projectId||artwork.concept_id!==conceptId||!asset||asset.projectId!==projectId||asset.ownerType!=='artwork'||asset.ownerId!==artworkId) return null; fs.unlinkSync(asset.storagePath); db.prepare('DELETE FROM image_assets WHERE id=?').run(assetId); const replacement=listAssets('artwork',artworkId)[0] ?? null; if(replacement) activateAsset(projectId,'artwork',artworkId,replacement.id); db.prepare('UPDATE project_artwork SET active_asset_id=?,updated_at=? WHERE id=?').run(replacement?.id ?? null,new Date().toISOString(),artworkId); return asArtwork(row(artworkId)); }
export async function refineArtwork(project:any,id:string,instruction:string) { const item=row(id),conceptId=requireSelectedConceptId(project.id); if(!item||item.project_id!==project.id||item.concept_id!==conceptId||!item.active_asset_id) throw new Error('Choose an artwork version first.'); const asset=findAsset(item.active_asset_id)!; const p=platformPresets[item.platform as PlatformId]; const result=await refineImage(project.image_provider,request(project,conceptId,item.platform,`${context(project,conceptId,item.platform,'Refined','Automatic','','','')} Refine the supplied image: ${instruction}. Preserve character identity, location, and intent.`,asset.quality as ImageQuality | undefined),fs.readFileSync(asset.storagePath),asset.originalFilename || 'artwork.png'); const next=await createGeneratedAsset({projectId:project.id,ownerType:'artwork',ownerId:id,url:result.url,provider:result.provider,model:result.model,quality:result.quality,resolution:result.resolution,tier:result.tier}); db.prepare('UPDATE project_artwork SET active_asset_id=?,updated_at=? WHERE id=?').run(next.id,new Date().toISOString(),id); return asArtwork(row(id)); }
