/** Central, provider-neutral publishing formats. Keep platform policy out of UI components. */
export type PlatformId = 'youtube' | 'youtube-shorts' | 'tiktok' | 'spotify' | 'landscape' | 'vertical' | 'square';
export type PlatformPreset = { id: PlatformId; displayName: string; aspectRatio: '16:9'|'9:16'|'1:1'; preferredResolution: '1536x1024'|'1024x1536'|'1024x1024'; orientation: 'landscape'|'vertical'|'square'; safeArea: string; compositionGuidance: string; artworkType: string; };
export const platformPresets: Record<PlatformId, PlatformPreset> = {
  youtube: { id:'youtube', displayName:'YouTube', aspectRatio:'16:9', preferredResolution:'1536x1024', orientation:'landscape', safeArea:'Keep faces, logos and title treatment away from the outer 10% of each edge.', compositionGuidance:'Landscape composition with a clear focal point and clean space for title overlays.', artworkType:'YouTube thumbnail' },
  'youtube-shorts': { id:'youtube-shorts', displayName:'YouTube Shorts', aspectRatio:'9:16', preferredResolution:'1024x1536', orientation:'vertical', safeArea:'Keep essential details centered; avoid the top and bottom 12% for interface overlays.', compositionGuidance:'Full-screen vertical composition; make the subject readable on a phone.', artworkType:'Shorts cover' },
  tiktok: { id:'tiktok', displayName:'TikTok', aspectRatio:'9:16', preferredResolution:'1024x1536', orientation:'vertical', safeArea:'Keep essential details centered; leave room at right and bottom for TikTok interface overlays.', compositionGuidance:'Vertical, full-screen composition with a strong central or left-third subject.', artworkType:'TikTok cover' },
  spotify: { id:'spotify', displayName:'Spotify', aspectRatio:'9:16', preferredResolution:'1024x1536', orientation:'vertical', safeArea:'Keep the focal point away from the extreme edges.', compositionGuidance:'Vertical Canvas-style visual with a clear, instantly recognizable focal point.', artworkType:'Spotify Canvas visual reference' },
  landscape: { id:'landscape', displayName:'Generic Landscape', aspectRatio:'16:9', preferredResolution:'1536x1024', orientation:'landscape', safeArea:'Keep important details within the center 80% of the frame.', compositionGuidance:'Balanced landscape composition.', artworkType:'Generic project cover' },
  vertical: { id:'vertical', displayName:'Generic Vertical', aspectRatio:'9:16', preferredResolution:'1024x1536', orientation:'vertical', safeArea:'Keep important details within the center 80% of the frame.', compositionGuidance:'Balanced vertical composition.', artworkType:'Generic project cover' },
  square: { id:'square', displayName:'Generic Square', aspectRatio:'1:1', preferredResolution:'1024x1024', orientation:'square', safeArea:'Keep essential details inside the central square.', compositionGuidance:'Centered square composition.', artworkType:'Generic project cover' },
};
export const allPlatformPresets = Object.values(platformPresets);
export const presetForAspectRatio = (aspectRatio: string) => allPlatformPresets.find(p => p.aspectRatio === aspectRatio) ?? platformPresets.landscape;
