import type { VisualConcept } from './visual-concepts.js';
import type { VisualIdentity, VisualReference } from './visual-identity.js';
import { buildSongContext } from './song-context.js';

export type StoryboardShotContent = { section: string; title: string; description: string; action: string; shotType: string; camera: string; mood: string; characterIds: string[]; locationId: string | null };
export type StoryboardApproach = 'narrative' | 'performance' | 'abstract' | 'mixed';
export type StoryboardPlan = { approach: StoryboardApproach; summary: string; narrativeArc: string; opening: string; midpoint: string; climax: string; ending: string; motifs: string[]; primaryCharacterIds: string[]; primaryLocationIds: string[]; pacingNotes: string };
type ProjectContext = { title: string; lyrics: string; suno_description?: string | null; visual_style: string; aspect_ratio: string; duration_seconds?: number | null };

function referenceList(items: VisualReference[]) { return items.map(item => `- ${item.id}: ${item.name} — ${item.description}`).join('\n') || '- None defined'; }
export function buildStoryboardContext(project: ProjectContext, identity: VisualIdentity, concept?: VisualConcept | null) {
  return `Project: ${project.title}\nUser visual direction: ${project.visual_style}\nAspect ratio: ${project.aspect_ratio}\nVisual Identity style: ${identity.style.description || project.visual_style}\nSelected Visual Concept: ${concept ? `${concept.title} — ${concept.description}. Mood: ${concept.mood}. Style: ${concept.visualStyle}. Lighting: ${concept.colorAndLighting}. Narrative: ${concept.narrativeDirection}` : 'None selected; follow the user visual direction.'}\nLocked characters (use their IDs only when appropriate):\n${referenceList(identity.characters.filter(item => item.locked))}\nLocked locations (use their IDs only when appropriate):\n${referenceList(identity.locations.filter(item => item.locked))}\nOther available characters:\n${referenceList(identity.characters.filter(item => !item.locked))}\nOther available locations:\n${referenceList(identity.locations.filter(item => !item.locked))}\n${buildSongContext(project)}`;
}
function approachDirection(approach: StoryboardApproach) { return { narrative: 'Use clear cause and effect, recurring people and places.', performance: 'Center performance imagery and intercut environments and details.', abstract: 'Favor symbolic, atmospheric interpretation over literal depiction.', mixed: 'Balance coherent narrative, symbolic imagery, and cinematic performance moments.' }[approach]; }
function detailDirection(detailLevel: number) {
  if (detailLevel <= 20) return 'Keep every shot extremely simple and concise: one clear subject, one clear action, basic framing, and a short mood. Avoid decorative or incidental details.';
  if (detailLevel <= 40) return 'Keep shots straightforward: describe the main subject, action, framing, and mood with only a few useful visual details.';
  if (detailLevel <= 60) return 'Use balanced cinematic detail: clearly describe subject, action, composition, camera, lighting, and atmosphere without overloading the shot.';
  if (detailLevel <= 80) return 'Use rich production detail: specify staging, subject placement, movement, lens or camera behavior, lighting, environment, and atmosphere.';
  return 'Make every shot extremely detailed and production-ready: precisely describe staging, subject placement, expression, movement, composition, lens and camera behavior, lighting, environment, texture, and atmosphere.';
}
export function buildStoryboardPrompt(input: { project: ProjectContext; identity: VisualIdentity; concept?: VisualConcept | null; shotCount: number; detailLevel: number; approach: StoryboardApproach }) { return `Create a coherent music-video storyboard with exactly ${input.shotCount} shots. First make an internal plan, then derive every shot from it.\n\n${buildStoryboardContext(input.project, input.identity, input.concept)}\n\nStoryboard approach: ${input.approach}. ${approachDirection(input.approach)}\n\nRequested shot detail: ${input.detailLevel}/100. ${detailDirection(input.detailLevel)} The detail level controls descriptive richness, not the number of events: every shot must still depict one feasible still-image moment.\n\nPlan requirements: define narrative, visual, character, location, and pacing progression; opening, midpoint escalation, climax, ending; and 1–3 recurring motifs. Prefer reference IDs and make wardrobe or location changes explicit. Interpret lyrics as themes, never a literal slideshow.\n\nShot requirements: maintain continuity and reuse established characters/locations. Give each a purpose (establish, introduce_character, build_tension, transition, reveal, emotional_closeup, motif, climax, resolve). Deliberately vary framing, angles, subject positions, and detail/environment shots to support pacing. Each is one feasible still image. characterIds/locationId must be listed IDs or []/null. ${input.project.duration_seconds ? `Use estimated startTime/endTime in seconds covering the ${input.project.duration_seconds}-second song.` : 'Set startTime and endTime to null.'}\n\nReturn ONLY JSON: {"plan":{"approach":"narrative|performance|abstract|mixed","summary":"...","narrativeArc":"...","opening":"...","midpoint":"...","climax":"...","ending":"...","motifs":["..."],"primaryCharacterIds":["reference-id"],"primaryLocationIds":["reference-id"],"pacingNotes":"..."},"shots":[{"startTime":number|null,"endTime":number|null,"section":"...","title":"...","description":"...","action":"...","shotType":"...","camera":"...","mood":"...","characterIds":["reference-id"],"locationId":"reference-id"|null}]}.`; }
export function buildShotRegenerationPrompt(input: { project: ProjectContext; identity: VisualIdentity; concept?: VisualConcept | null; detailLevel: number; plan: StoryboardPlan; previous?: StoryboardShotContent; current: StoryboardShotContent; next?: StoryboardShotContent }) { const compact = (shot?: StoryboardShotContent) => shot ? JSON.stringify(shot) : 'None'; return `Regenerate only the current storyboard shot. Preserve its role, nearby continuity, characters, location, and timing unless an explicit correction is needed.\n\n${buildStoryboardContext(input.project, input.identity, input.concept)}\n\nRequested shot detail: ${input.detailLevel}/100. ${detailDirection(input.detailLevel)} The detail level controls descriptive richness, not the number of events: the shot must still depict one feasible still-image moment.\n\nStoryboard plan: ${JSON.stringify(input.plan)}\nPrevious shot: ${compact(input.previous)}\nCurrent shot: ${compact(input.current)}\nNext shot: ${compact(input.next)}\n\nReturn ONLY JSON: {"section":"...","title":"...","description":"...","action":"...","shotType":"...","camera":"...","mood":"...","characterIds":["reference-id"],"locationId":"reference-id"|null}. Use only provided reference IDs.`; }
export function buildStoryboardReviewPrompt(input: { project: { title: string; visual_style: string; lyrics: string; suno_description?: string | null }; plan: StoryboardPlan | null; identity: VisualIdentity; concept?: VisualConcept | null; shots: { id: string; order: number; section: string; title: string; description: string; action: string; shotType: string; camera: string; mood: string; characterIds: string[]; locationId: string | null; imageUrl?: string | null }[] }) {
  const references = [...input.identity.characters, ...input.identity.locations].map(item => `${item.id}: ${item.name} — ${item.description}`).join('\n') || 'None';
  const shots = input.shots.map(shot => ({ ...shot, imageAvailable: Boolean(shot.imageUrl), imageUrl: undefined }));
  return `Review this music-video storyboard for possible visual and narrative consistency issues. This is advisory criticism, not objective fact. Do not propose automatic changes and do not invent details not present in the context. Assess character and location continuity, visual style, shot variety, narrative progression, motifs, and assigned references. Text-only review is valid; images may be available but are not evidence unless directly supplied.\n\nProject: ${input.project.title}\nVisual direction: ${input.project.visual_style}\nSelected concept: ${input.concept ? `${input.concept.title} — ${input.concept.description}; ${input.concept.visualStyle}; ${input.concept.colorAndLighting}` : 'None'}\nVisual identity style: ${input.identity.style.description}\nReferences:\n${references}\nPlan: ${JSON.stringify(input.plan)}\nShots: ${JSON.stringify(shots)}\n\nReturn ONLY JSON: {"summary":"brief balanced summary","score":number|null,"issues":[{"severity":"info|warning|important","category":"CHARACTER CONTINUITY|LOCATION CONTINUITY|VISUAL STYLE|SHOT VARIETY|NARRATIVE|MOTIFS|REFERENCE CONSISTENCY","title":"Possible issue","description":"Cautious practical observation","shotIds":["only IDs from Shots"],"suggestion":"Consider a manual change"}]}. Include only useful issues; use cautious wording such as May, Possible, or Consider.`;
}
export type ImageGenerationInput = { visualStyle: string; concept: { title: string; description: string; mood: string; visualStyle: string; colorAndLighting: string } | null; characters: { name: string; description: string }[]; location: { name: string; description: string } | null; description: string; action: string; shotType: string; camera: string; mood: string; previousShot?: { description: string; action: string; locationId: string | null } | null; generationInstructions?: string };
export function buildImagePrompt(input: ImageGenerationInput) {
  return `Music-video storyboard keyframe. Visual style: ${input.visualStyle}. ${input.concept ? `Selected visual concept: ${input.concept.title}. ${input.concept.description}. Mood: ${input.concept.mood}. Lighting: ${input.concept.colorAndLighting}.` : ''} ${input.characters.map(item => `Character reference — ${item.name}: ${item.description}. Preserve this character's recognizable appearance and wardrobe.`).join(' ')} ${input.location ? `Location reference — ${input.location.name}: ${input.location.description}. Preserve environmental continuity.` : ''} ${input.previousShot ? `Previous-shot continuity: ${input.previousShot.description}; action: ${input.previousShot.action}.` : ''} Shot: ${input.description}. Action: ${input.action}. Composition: ${input.shotType}; camera: ${input.camera}. Mood: ${input.mood}. ${input.generationInstructions || ''} No text, captions, logos, or watermarks.`;
}
