import { useEffect, useState } from 'react';

const API = 'http://localhost:3001/api';
type Quality = 'draft' | 'standard' | 'best';
type Project = { id: string; image_provider: 'openai' | 'grok'; image_quality_preset?: Quality; image_model_override?: string | null; image_resolution_override?: string | null };
type Model = { provider: 'openai' | 'grok'; modelId: string; displayName: string; supportedQualities: Quality[]; supportedResolutions: string[]; recommendedUse: string };

export function ProjectImageSettings({ project, onSaved }: { project: Project; onSaved: () => Promise<void> }) {
  const [advanced, setAdvanced] = useState(false); const [models, setModels] = useState<Model[]>([]); const [provider, setProvider] = useState(project.image_provider); const [quality, setQuality] = useState<Quality>(project.image_quality_preset ?? 'standard'); const [model, setModel] = useState(project.image_model_override ?? ''); const [resolution, setResolution] = useState(project.image_resolution_override ?? ''); const [message, setMessage] = useState('');
  useEffect(() => { void fetch(`${API}/settings/providers`).then(r => r.json()).then(r => setModels(r.imageModels ?? [])).catch(() => setMessage('Could not load image options.')); }, []);
  const available = models.filter(item => item.provider === provider); const selected = available.find(item => item.modelId === model); const qualities = selected?.supportedQualities ?? ['draft', 'standard', 'best']; const resolutions = selected?.supportedResolutions ?? [];
  const save = async () => { setMessage(''); const response = await fetch(`${API}/projects/${project.id}/image-settings`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ imageProvider: provider, qualityPreset: quality, modelOverride: model || null, resolutionOverride: resolution || null }) }); if (!response.ok) { setMessage((await response.json()).error || 'Could not save image settings.'); return; } setMessage('Image settings saved. They do not generate images.'); await onSaved(); };
  return <section className="generation-settings"><h2>Image quality</h2><p>Choose a preset for storyboard previews. Changing settings never creates images.</p><label>Preset<select value={quality} onChange={e => setQuality(e.target.value as Quality)}><option value="draft" disabled={!qualities.includes('draft')}>Draft (cheapest)</option><option value="standard" disabled={!qualities.includes('standard')}>Standard</option><option value="best" disabled={!qualities.includes('best')}>Best</option></select></label><button className="advanced-toggle" onClick={() => setAdvanced(!advanced)}>Advanced settings <span>{advanced ? '⌃' : '⌄'}</span></button>{advanced && <div className="advanced-fields"><label>Image provider<select value={provider} onChange={e => { setProvider(e.target.value as typeof provider); setModel(''); setResolution(''); }}><option value="openai">OpenAI</option><option value="grok">Grok</option></select></label><label>Image model<select value={model} onChange={e => { const next = available.find(item => item.modelId === e.target.value); setModel(e.target.value); setResolution(''); if (next && !next.supportedQualities.includes(quality)) setQuality(next.supportedQualities[0]); }}><option value="">Use quality recommendation</option>{available.map(item => <option key={item.modelId} value={item.modelId}>{item.displayName}</option>)}</select></label>{selected && <label>Resolution<select value={resolution} onChange={e => setResolution(e.target.value)}><option value="">Use recommended resolution</option>{resolutions.map(item => <option key={item}>{item}</option>)}</select></label>}<label className="reference-toggle"><span>Reference images<small>Use references from Visual Identity</small></span><input type="checkbox" defaultChecked /></label></div>}<button className="save-settings" onClick={() => void save()}>Save image settings</button>{message && <p className="settings-message">{message}</p>}</section>;
}
