import { useEffect, useState } from 'react';
import { Button, Collapse, Select, Stack, Switch, Text } from '@mantine/core';

const API = 'http://localhost:3001/api';
type Quality = 'draft' | 'standard' | 'best';
type Project = { id: string; image_provider: 'openai' | 'grok'; image_quality_preset?: Quality; image_model_override?: string | null; image_resolution_override?: string | null };
type Model = { provider: 'openai' | 'grok'; modelId: string; displayName: string; supportedQualities: Quality[]; supportedResolutions: string[]; recommendedUse: string };

export function ProjectImageSettings({ project, onSaved }: { project: Project; onSaved: () => Promise<void> }) {
  const [advanced, setAdvanced] = useState(false); const [models, setModels] = useState<Model[]>([]); const [provider, setProvider] = useState(project.image_provider); const [quality, setQuality] = useState<Quality>(project.image_quality_preset ?? 'standard'); const [model, setModel] = useState(project.image_model_override ?? ''); const [resolution, setResolution] = useState(project.image_resolution_override ?? ''); const [message, setMessage] = useState('');
  useEffect(() => { void fetch(`${API}/settings/providers`).then(r => r.json()).then(r => setModels(r.imageModels ?? [])).catch(() => setMessage('Could not load image options.')); }, []);
  useEffect(() => { setProvider(project.image_provider); setQuality(project.image_quality_preset ?? 'standard'); setModel(project.image_model_override ?? ''); setResolution(project.image_resolution_override ?? ''); }, [project.id]);
  const available = models.filter(item => item.provider === provider); const selected = available.find(item => item.modelId === model); const qualities = selected?.supportedQualities ?? ['draft', 'standard', 'best']; const resolutions = selected?.supportedResolutions ?? [];
  const save = async () => { setMessage(''); const response = await fetch(`${API}/projects/${project.id}/image-settings`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ imageProvider: provider, qualityPreset: quality, modelOverride: model || null, resolutionOverride: resolution || null }) }); if (!response.ok) { setMessage((await response.json()).error || 'Could not save image settings.'); return; } setMessage('Image settings saved. They do not generate images.'); await onSaved(); };
  return <Stack className="generation-settings"><h2>Image generation</h2><Text>Choose the default quality for all generated images. You can override it in each generation window without changing this default.</Text><Select label="Default image quality" value={quality} onChange={value => setQuality((value || 'standard') as Quality)} data={[{value:'draft',label:'Draft (cheapest)',disabled:!qualities.includes('draft')},{value:'standard',label:'Standard',disabled:!qualities.includes('standard')},{value:'best',label:'Best',disabled:!qualities.includes('best')}]}/><Button variant="subtle" justify="space-between" onClick={() => setAdvanced(!advanced)}>Advanced settings <span>{advanced ? '⌃' : '⌄'}</span></Button><Collapse expanded={advanced}><Stack className="advanced-fields"><Select label="Image provider" value={provider} onChange={value => { setProvider((value || 'openai') as typeof provider); setModel(''); setResolution(''); }} data={[{value:'openai',label:'OpenAI'},{value:'grok',label:'Grok'}]}/><Select label="Image model" value={model} onChange={value => { const next = available.find(item => item.modelId === value); setModel(value || ''); setResolution(''); if (next && !next.supportedQualities.includes(quality)) setQuality(next.supportedQualities[0]); }} data={[{value:'',label:'Use quality recommendation'}, ...available.map(item => ({value:item.modelId,label:item.displayName}))]}/>{selected && <Select label="Resolution" value={resolution} onChange={value => setResolution(value || '')} data={[{value:'',label:'Use recommended resolution'}, ...resolutions]}/>}<Switch label="Reference images" description="Use references from Visual Identity" defaultChecked /></Stack></Collapse><Button variant="default" className="save-settings" onClick={() => void save()}>Save image settings</Button>{message && <Text className="settings-message">{message}</Text>}</Stack>;
}
