import { useEffect, useState } from 'react';
import { WorkspaceHeader } from './AppLayout';
import { Alert, Button, Checkbox, Paper, Select, Stack, Text, Textarea } from '@mantine/core';
import { ProjectImageSettings } from './ProjectImageSettings';

const API='http://localhost:3001/api';
const targetLabels:Record<string,string>={youtube:'YouTube','youtube-shorts':'YouTube Shorts',tiktok:'TikTok',spotify:'Spotify',landscape:'Generic Landscape',vertical:'Generic Vertical',square:'Generic Square'};
type Project={id:string;project_type?:'general'|'music_video';creative_brief?:string;visual_style?:string;lyrics?:string;suno_description?:string|null;publishing_targets?:string;primary_visual_format?:string;image_provider:'openai'|'grok';image_quality_preset?:'draft'|'standard'|'best';image_model_override?:string|null;image_resolution_override?:string|null};

export function ProjectDetails({project,onSaved}:{project:Project;onSaved:()=>Promise<void>}){
  const [projectType,setProjectType]=useState(project.project_type??'music_video');
  const [creativeBrief,setCreativeBrief]=useState(project.creative_brief??'');
  const [visualStyle,setVisualStyle]=useState(project.visual_style??'');
  const [lyrics,setLyrics]=useState(project.lyrics??'');
  const [sunoDescription,setSunoDescription]=useState(project.suno_description??'');
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[failed,setFailed]=useState(false);
  const [targets,setTargets]=useState<string[]>(()=>JSON.parse(project.publishing_targets||'[]'));
  const [primary,setPrimary]=useState(project.primary_visual_format||'landscape');
  useEffect(()=>{setProjectType(project.project_type??'music_video');setCreativeBrief(project.creative_brief??'');setVisualStyle(project.visual_style??'');setLyrics(project.lyrics??'');setSunoDescription(project.suno_description??'');},[project.id,project.project_type,project.creative_brief,project.visual_style,project.lyrics,project.suno_description]);
  async function save(){setBusy(true);setMessage('');setFailed(false);try{const response=await fetch(`${API}/projects/${project.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectType,creativeBrief,visualStyle,lyrics,sunoDescription})});if(!response.ok)throw new Error((await response.json()).error||'Could not save project information.');await onSaved();setMessage('Project information saved. Existing concepts, storyboards, and images remain unchanged.');}catch(error){setFailed(true);setMessage(error instanceof Error?error.message:'Could not save project information.');}finally{setBusy(false)}}
  async function savePublishing(){setBusy(true);setMessage('');setFailed(false);try{const response=await fetch(`${API}/projects/${project.id}/publishing`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({publishingTargets:targets,primaryVisualFormat:targets.includes(primary)?primary:(targets[0]||'landscape')})});if(!response.ok)throw new Error((await response.json()).error||'Could not save publishing targets.');await onSaved();setMessage('Publishing targets saved. No images were generated or changed.');}catch(error){setFailed(true);setMessage(error instanceof Error?error.message:'Could not save publishing targets.');}finally{setBusy(false)}}
  return <main><WorkspaceHeader title="General settings" description="Manage the project brief, optional music context, and generation defaults."/>
    <Paper className="panel project-details" p="lg"><ProjectImageSettings project={project} onSaved={onSaved}/></Paper>
    <Paper className="panel project-details" p="lg"><Stack><h2>Project information</h2><Select label="Project type" value={projectType} onChange={value=>setProjectType((value||'general') as 'general'|'music_video')} allowDeselect={false} data={[{value:'general',label:'General concept'},{value:'music_video',label:'Music video'}]}/><Textarea label="Creative brief" description="The main idea, purpose, subjects, themes, audience, or intended result." autosize minRows={5} maxRows={24} resize="vertical" value={creativeBrief} onChange={event=>setCreativeBrief(event.target.value)} placeholder="Describe what you want to develop…"/><Textarea label="Visual direction" description="Optional guidance for style, medium, mood, palette, lighting, or visual references." autosize minRows={3} maxRows={16} resize="vertical" value={visualStyle} onChange={event=>setVisualStyle(event.target.value)} placeholder="Describe how the project should look…"/>{projectType==='music_video'&&<><Textarea label="SUNO description (optional)" autosize minRows={4} maxRows={16} resize="vertical" value={sunoDescription} onChange={event=>setSunoDescription(event.target.value)} placeholder="Paste the original SUNO song description or prompt here."/><Textarea label="Lyrics (optional)" autosize minRows={6} maxRows={24} resize="vertical" value={lyrics} onChange={event=>setLyrics(event.target.value)} placeholder="Paste or update the song lyrics here."/></>}<Text size="sm" c="dimmed">Switching project type hides music fields but never deletes their saved values.</Text><Button loading={busy} onClick={()=>void save()}>Save project information</Button></Stack></Paper>
    <Paper className="panel project-details" p="lg"><Stack><h2>Publishing targets</h2><Text>Targets guide future generation and artwork only. Existing images are never regenerated.</Text>{Object.entries(targetLabels).map(([id,label])=><Checkbox key={id} label={label} checked={targets.includes(id)} onChange={event=>setTargets(event.target.checked?[...targets,id]:targets.filter(item=>item!==id))}/>) }<Select label="Primary visual format" value={targets.includes(primary)?primary:(targets[0]||'landscape')} onChange={value=>setPrimary(value||'landscape')} data={(targets.length?targets:['landscape']).map(id=>({value:id,label:targetLabels[id]}))}/><Button loading={busy} onClick={()=>void savePublishing()}>Save publishing targets</Button>{message&&<Alert color={failed?'red':'green'}>{message}</Alert>}</Stack></Paper>
  </main>;
}
